# Generated by Django 3.1.4 on 2021-01-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='minidesc',
            field=models.TextField(default='default.jpg'),
            preserve_default=False,
        ),
    ]
